language: csharp
solution: TimeSync.sln 
install:
  - nuget restore TimeSync.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TimeSync.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TestTimeSync/bin/Release/TestTimeSync.dll