// This file has been generated by the GUI designer. Do not modify.

using Gtk;
using Mono.Unix;
using Stetic;

public partial class MainWindow
{
    protected virtual void Build()
    {
        Gui.Initialize(this);
        // Widget MainWindow
        Name = "MainWindow";
        Title = Catalog.GetString("MainWindow");
        WindowPosition = ((WindowPosition) (4));
        if ((Child != null))
        {
            Child.ShowAll();
        }
        DefaultWidth = 400;
        DefaultHeight = 300;
        Show();
        DeleteEvent += OnDeleteEvent;
    }
}